modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/HermitOwO/TFC-CastIronGrill/issues"
license = "MIT"

[[mods]]
modId = "castirongrill"
version = "${file.jarVersion}"
displayName = "TFC Cast Iron Grill"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tfc-cast-iron-grill"
authors = "HermitOwO"
description = '''Cast iron grill addon for TFC.'''

[[dependencies.castirongrill]]
modId = "forge"
mandatory = true
versionRange = "[47.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.castirongrill]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.castirongrill]]
modId = "tfc"
mandatory = true
versionRange = "[3.1.2-beta,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.castirongrill]]
modId = "firmalife"
mandatory = false
versionRange = "[2.0.0-beta,)"
ordering = "AFTER"
side = "BOTH"
